site_name: OpenMarketIQ Python API
site_url: https://yourdomain.com
nav:
  - Home: index.md
  - Usage: usage.md
theme:
  name: material
  logo: OpenMarketIQ_Logo_small.png
  favicon: ../assets/OpenMarketIQ favicon-32x32.png
repo_url: https://github.com/OpenMarketIQ/OpenMarketIQ
repo_name: OpenMarketIQ/OpenMarketIQ 